name: Build and Deploy Spring Boot to Azure

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the Spring Boot app using Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # Deploy to Azure App Service using Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: carbon-offset-estimation-ms       # e.g., springboot-microservice
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
